version: '3'
services:
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    networks:
    - mern-app
    depends_on:
    - mongo
    - backend
  
  backend:
    build: ./backend
    container_name: backend_container
    networks:
    - mern-app
    ports:
    - 4000:4000
    depends_on:
    - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - mern-app

    volumes:
      - db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - mern-app
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
  
networks:
  mern-app:
    driver: bridge

volumes:
  db-data:
    driver: local
